name: Testes e2e

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "HOST=0.0.0.0" > .env
          echo "PORT=1337" >> .env
          echo "APP_KEYS=$(openssl rand -base64 32),$(openssl rand -base64 32)" >> .env
          echo "API_TOKEN_SALT=$(openssl rand -base64 32)" >> .env
          echo "ADMIN_JWT_SECRET=$(openssl rand -base64 32)" >> .env
          echo "TRANSFER_TOKEN_SALT=$(openssl rand -base64 32)" >> .env
          echo "JWT_SECRET=$(openssl rand -base64 32)" >> .env
          echo "DATABASE_CLIENT=sqlite" >> .env
          echo "DATABASE_FILENAME=.tmp/data.db" >> .env

      - name: Build Strapi
        run: npm run build

      - name: Run e2e tests
        run: npm run ci:e2e
